# 指定API版本为v1，这是Kubernetes中定义Service的基本版本
apiVersion: v1
# 指定Kubernetes资源的类型为Service，Service用于定义一组Pod的网络接口
kind: Service
# metadata部分用于定义Service的元数据
metadata:
  # name字段指定Service的名称为lmbook-record-mysql
  name: lmbook-record-mysql
# spec部分用于定义Service的规格
spec:
  # selector字段用于选择要暴露的Pod，这里选择标签为app=lmbook-record-mysql的Pod
  selector:
    app: lmbook-record-mysql
  # ports字段定义Service的端口配置
  ports:

    # 定义一个端口配置
    - protocol: TCP  # 指定协议为TCP
      port: 3308     # 指定Service对外暴露的端口为3308
      targetPort: 3306  # 指定Service将流量转发到Pod的端口为3306
  # type字段定义Service的类型，LoadBalancer表示使用云提供商的负载均衡器
  type: LoadBalancer