// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"basic-go/lmbook/interactive/grpc"
	"basic-go/lmbook/interactive/ioc"
	"basic-go/lmbook/interactive/repository"
	"basic-go/lmbook/interactive/repository/cache"
	"basic-go/lmbook/interactive/repository/dao"
	"basic-go/lmbook/interactive/service"
	"github.com/google/wire"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitSaramaClient()
	loggerV1 := ioc.InitLogger()
	srcDB := ioc.InitSrcDB()
	dstDB := ioc.InitDstDB()
	syncProducer := ioc.InitSaramaSyncProducer(client)
	producer := ioc.InitInteractiveProducer(syncProducer)
	mySQLBinlogConsumer := ioc.InitInteractiveReadEventConsumer(client, loggerV1, srcDB, dstDB, producer)
	consumer := ioc.InitFixerConsumer(client, loggerV1, srcDB, dstDB)
	v := ioc.InitConsumers(mySQLBinlogConsumer, consumer)
	doubleWritePool := ioc.InitDoubleWritePool(srcDB, dstDB)
	db := ioc.InitBizDB(doubleWritePool)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerV1)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerV1)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.NewGrpcxServer(interactiveServiceServer, loggerV1)
	ginxServer := ioc.InitGinxServer(loggerV1, srcDB, dstDB, doubleWritePool, producer)
	app := &App{
		consumers:   v,
		server:      server,
		adminServer: ginxServer,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitSrcDB, ioc.InitDstDB, ioc.InitDoubleWritePool, ioc.InitBizDB, ioc.InitLogger, ioc.InitSaramaClient, ioc.InitSaramaSyncProducer, ioc.InitRedis)

var interactiveSvcSet = wire.NewSet(dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache, repository.NewCachedInteractiveRepository, service.NewInteractiveService)
