// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"basic-go/lmbook/bff/ioc"
	"basic-go/lmbook/bff/web"
	"basic-go/lmbook/bff/web/jwt"
	"basic-go/lmbook/pkg/wego"
)

// Injectors from wire.go:

func InitApp() *wego.App {
	loggerV1 := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisHandler(cmdable)
	client := ioc.InitEtcdClient()
	userServiceClient := ioc.InitUserClient(client)
	codeServiceClient := ioc.InitCodeClient(client)
	userHandler := web.NewUserHandler(userServiceClient, codeServiceClient, handler)
	articleServiceClient := ioc.InitArticleClient(client)
	interactiveServiceClient := ioc.InitIntrClient(client)
	rewardServiceClient := ioc.InitRewardClient(client)
	articleHandler := web.NewArticleHandler(articleServiceClient, interactiveServiceClient, rewardServiceClient, loggerV1)
	rewardHandler := web.NewRewardHandler(rewardServiceClient, articleServiceClient)
	server := ioc.InitGinServer(loggerV1, handler, userHandler, articleHandler, rewardHandler)
	app := &wego.App{
		WebServer: server,
	}
	return app
}
