// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"basic-go/lmbook/tag/events"
	"basic-go/lmbook/tag/grpc"
	"basic-go/lmbook/tag/repository/cache"
	"basic-go/lmbook/tag/repository/dao"
	"basic-go/lmbook/tag/service"
)

// Injectors from wire.go:

func InitGRPCService(p events.Producer) *grpc.TagServiceServer {
	gormDB := InitTestDB()
	tagDAO := dao.NewGORMTagDAO(gormDB)
	cmdable := InitRedis()
	tagCache := cache.NewRedisTagCache(cmdable)
	loggerV1 := InitLog()
	tagRepository := InitRepository(tagDAO, tagCache, loggerV1)
	tagService := service.NewTagService(tagRepository, p, loggerV1)
	tagServiceServer := grpc.NewTagServiceServer(tagService)
	return tagServiceServer
}
